version: '3.1'
services:
  web:
    image: odoo:14.0
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data-copy:/var/lib/odoo
      - odoo-web-config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
     - odoo-db-data-copy:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data-copy:
  odoo-db-data-copy:
  odoo-web-config: